#!/bin/bash


#min top1 err - healthy
python tools/extractlogit_net.py   --cfg configs/X3D_M_stroke_withcropping_logit_extraction.yaml   DATA.PATH_TO_DATA_DIR    preprocessing/splits/split1/test_stroke     NUM_GPUS 2   TRAIN.BATCH_SIZE 128   DATA.DECODING_BACKEND pyav   OUTPUT_DIR models/X3D_M_stroke_HC_model_all_split1   TEST.ENABLE True   TRAIN.ENABLE False   TEST.NUM_ENSEMBLE_VIEWS 1   DATA.TARGET_FPS  60   MODEL.NUM_CLASSES 5   TEST.CHECKPOINT_FILE_PATH  models/X3D_M_stroke_HC_model_all_split1/checkpoints/checkpoint_epoch_00009.pyth    DATA.RANDOM_FLIP False   TEST.SAVE_RESULTS_PATH    extracted_logits/all_HC_split1_best_err/test_stroke   DATA.SAMPLING_RATE 4;

python tools/extractlogit_net.py   --cfg configs/X3D_M_stroke_withcropping_logit_extraction.yaml   DATA.PATH_TO_DATA_DIR    preprocessing/splits/split2/test_stroke     NUM_GPUS 2   TRAIN.BATCH_SIZE 128   DATA.DECODING_BACKEND pyav   OUTPUT_DIR models/X3D_M_stroke_HC_model_all_split2   TEST.ENABLE True   TRAIN.ENABLE False   TEST.NUM_ENSEMBLE_VIEWS 1   DATA.TARGET_FPS  60   MODEL.NUM_CLASSES 5   TEST.CHECKPOINT_FILE_PATH  models/X3D_M_stroke_HC_model_all_split2/checkpoints/checkpoint_epoch_00012.pyth    DATA.RANDOM_FLIP False   TEST.SAVE_RESULTS_PATH    extracted_logits/all_HC_split2_best_err/test_stroke   DATA.SAMPLING_RATE 4;

python tools/extractlogit_net.py   --cfg configs/X3D_M_stroke_withcropping_logit_extraction.yaml   DATA.PATH_TO_DATA_DIR    preprocessing/splits/split3/test_stroke     NUM_GPUS 2   TRAIN.BATCH_SIZE 128   DATA.DECODING_BACKEND pyav   OUTPUT_DIR models/X3D_M_stroke_HC_model_all_split3   TEST.ENABLE True   TRAIN.ENABLE False   TEST.NUM_ENSEMBLE_VIEWS 1   DATA.TARGET_FPS  60   MODEL.NUM_CLASSES 5   TEST.CHECKPOINT_FILE_PATH  models/X3D_M_stroke_HC_model_all_split3/checkpoints/checkpoint_epoch_00008.pyth    DATA.RANDOM_FLIP False   TEST.SAVE_RESULTS_PATH    extracted_logits/all_HC_split3_best_err/test_stroke   DATA.SAMPLING_RATE 4;

python tools/extractlogit_net.py   --cfg configs/X3D_M_stroke_withcropping_logit_extraction.yaml   DATA.PATH_TO_DATA_DIR    preprocessing/splits/split4/test_stroke     NUM_GPUS 2   TRAIN.BATCH_SIZE 128   DATA.DECODING_BACKEND pyav   OUTPUT_DIR models/X3D_M_stroke_HC_model_all_split4   TEST.ENABLE True   TRAIN.ENABLE False   TEST.NUM_ENSEMBLE_VIEWS 1   DATA.TARGET_FPS  60   MODEL.NUM_CLASSES 5   TEST.CHECKPOINT_FILE_PATH  models/X3D_M_stroke_HC_model_all_split4/checkpoints/checkpoint_epoch_00013.pyth    DATA.RANDOM_FLIP False   TEST.SAVE_RESULTS_PATH    extracted_logits/all_HC_split4_best_err/test_stroke   DATA.SAMPLING_RATE 4;
